DROP TABLE History;
DROP TABLE Solutions;
DROP TABLE Users;
DROP TABLE Levels;


CREATE TABLE Users(
UserID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Username VARCHAR (20) NOT NULL CHECK (LEN(Username) > 4),
Password VARCHAR (30) NOT NULL CHECK (LEN(Password) > 5),
Score INT NOT NULL DEFAULT 0,
UserType CHAR(1) NOT NULL CHECK (UserType = 'M' OR UserType = 'A'),
Email VARCHAR (70) NOT NULL UNIQUE CHECK (LEN(Email) > 5),
Country VARCHAR (70) DEFAULT 'Unknown'
);

CREATE TABLE History(
HistoryID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
UserID INT NOT NULL CHECK (UserID > 0),
LevelID INT NOT NULL CHECK (LevelID > 0),
Time TIME NOT NULL,
Score INT NOT NULL,
DateTime SMALLDATETIME NOT NULL
);

CREATE TABLE Levels(
LevelID  INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Name VARCHAR (30) NOT NULL, 
SizeX INT NOT NULL CHECK (SizeX >= 10 AND SizeX <= 99),
SizeY INT NOT NULL CHECK (SizeY >= 10 AND SizeY <= 99),
Letters VARCHAR (MAX) NOT NULL,
CONSTRAINT ck_letters_size CHECK(LEN(Letters) = (SizeX * SizeY))
);

CREATE TABLE Solutions(
SolutionID  INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
LevelID INT NOT NULL,
Word VARCHAR (20) NOT NULL
UNIQUE (LevelID, Word)
);

ALTER TABLE History
ADD CONSTRAINT FK_History_Users
FOREIGN KEY (UserID) REFERENCES Users(UserID);

ALTER TABLE History
ADD CONSTRAINT FK_History_Levels
FOREIGN KEY (LevelID) REFERENCES Levels(LevelID);

ALTER TABLE Solutions
ADD CONSTRAINT FK_Solutions_Levels
FOREIGN KEY (LevelID) REFERENCES Levels(LevelID);

